name: Build and deploy game

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install trunk
        uses: jetli/trunk-action@v0.2.0
        with:
          version: 'latest'

      - name: Install wasm32 target
        run: rustup target add wasm32-unknown-unknown

        # The TRUNK_BUILD_PUBLIC_URL is to make sure relative paths work in a GH pages project
      - name: Build
        run: env TRUNK_BUILD_PUBLIC_URL="./" trunk build --release

      - name: Deploy to target branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
